# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.communicator = "winrm"
  config.windows.set_work_network = true
  config.vm.box = "windows10_vs2017_fusion"
  config.vm.guest = :windows
  config.windows.halt_timeout = 15

  config.vm.define "dev" do |dev|
      dev.vm.hostname = "dev"

      dev.vm.provision :shell, path: "scripts/Install-Chocolatey.ps1"
      dev.vm.provision :shell, path: "scripts/Install-Apps.ps1"

      dev.vm.provider "vmware_fusion" do |provider|
          provider.name = "dev"
          provider.gui = true
          provider.vmx['memsize'] = 8192
          provider.vmx['numvcpus'] = 2
		  provider.vmx["ethernet0.pcislotnumber"] = "192"
      end
  end
end
